import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {BookOpen,LayoutDashboard,Users,ClipboardCheck,NotebookPen,ChartColumn,Settings,Plus,ArrowRight,GraduationCap,LogOut,Check,CalendarDays,ChevronRight,Cloud,FlaskConical,Search,X} from 'lucide-react';
import {signInWithEmailAndPassword,onAuthStateChanged,signOut} from 'firebase/auth';
import {collection,onSnapshot,setDoc,doc} from 'firebase/firestore';
import {configured,auth,db} from './firebase';
import {emptyData,demoData,csv,validateMeeting} from './domain';
import {Field,Empty,Modal,MeetingRow} from './ui';
import {Attendance,Journal,Grades,SettingsForm,Editor} from './forms';
import Reports from './Reports';
import {exportReport} from './native';
import './style.css';
const menus=[['home','Ringkasan',LayoutDashboard],['meetings','Pertemuan & absen',ClipboardCheck],['journal','Jurnal mengajar',NotebookPen],['grades','Penilaian',BookOpen],['classes','Kelas & siswa',Users],['reports','Laporan',ChartColumn],['settings','Pengaturan',Settings]];
export default function App(){
 const[mode,setMode]=useState('login'),[user,setUser]=useState(null),[data,setData]=useState(emptyData),[page,setPage]=useState('home'),[classId,setClassId]=useState(''),[subjectId,setSubjectId]=useState(''),[selected,setSelected]=useState(''),[modal,setModal]=useState(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[search,setSearch]=useState('');
 useEffect(()=>{if(!auth)return;return onAuthStateChanged(auth,u=>{setUser(u);if(u){setData(emptyData());setLoading(true);setMode('cloud')}else setMode(m=>m==='cloud'?'login':m)})},[]);
 useEffect(()=>{if(mode!=='cloud'||!user)return;return onSnapshot(collection(db,'users',user.uid,'records'),snap=>{const next=emptyData();snap.forEach(d=>{const {kind,...value}=d.data();if(kind==='profile')next.profile=value;else if(Array.isArray(next[kind]))next[kind].push({...value,id:d.id})});setData(next);setLoading(false)},()=>{setLoading(false);setNotice('Data tidak dapat dibaca. Periksa koneksi dan aturan akses Firebase.');})},[mode,user]);
 useEffect(()=>{if(notice){const t=setTimeout(()=>setNotice(''),6500);return()=>clearTimeout(t)}},[notice]);
 async function save(kind,value){setBusy(true);try{if(mode==='cloud'){await setDoc(doc(db,'users',user.uid,'records',kind==='profile'?'profile':value.id),{...value,kind})}else{const next={...data,[kind]:kind==='profile'?value:[...data[kind].filter(x=>x.id!==value.id),value]};localStorage.setItem('ruang-guru-demo-v1',JSON.stringify(next));setData(next)}setNotice('Perubahan tersimpan'+(mode==='demo'?' di perangkat ini.':'.'));return true}catch(e){setNotice('Gagal menyimpan. Periksa koneksi atau ruang penyimpanan, lalu coba lagi.');return false}finally{setBusy(false)}}
 function startDemo(){try{const raw=localStorage.getItem('ruang-guru-demo-v1');setData(raw?JSON.parse(raw):demoData());setMode('demo')}catch{setNotice('Penyimpanan demo tidak tersedia. Izinkan penyimpanan browser.')}}
 async function logout(){if(mode==='cloud')await signOut(auth);setMode('login');setData(emptyData());setSelected('');setClassId('');setSubjectId('')}
 const cls=data.classes.find(c=>c.id===classId)||data.classes[0];const cid=cls?.id||'';
 const subjects=data.subjects.filter(s=>s.classIds.includes(cid));const subject=subjects.find(s=>s.id===subjectId)||subjects[0];const sid=subject?.id||'';
 const meetings=data.meetings.filter(m=>m.classId===cid&&m.subjectId===sid&&m.year===data.profile.year&&m.semester===data.profile.semester).sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time));
 const current=meetings.find(m=>m.id===selected);const students=data.students.filter(s=>s.classId===cid).sort((a,b)=>a.name.localeCompare(b.name));
 const allCurrent=data.meetings.filter(m=>m.year===data.profile.year&&m.semester===data.profile.semester);
 function openMeeting(m,p='meetings'){setSelected(m.id);setPage(p)}
 function newMeeting(){if(!cls||!subject||!students.length){setNotice('Siapkan kelas, mapel, dan siswa terlebih dahulu.');setPage('classes');return}setModal({type:'meeting'})}
 async function exportRows(rows,name){try{await exportReport(csv(rows),name)}catch{setNotice('Ekspor gagal. Coba lagi atau gunakan versi web.')}}
 if(mode==='login')return <main className="login"><section className="login-story"><div className="brand"><span><BookOpen/></span>Ruang Guru</div><div><div className="eyebrow">RUANG UNTUK MENGAJAR LEBIH BAIK</div><h1>Setiap pertemuan,<br/>bermakna.</h1><p>Jurnal, kehadiran, dan perkembangan belajar siswa. Tertata dalam satu ruang kerja Anda.</p><div className="login-tags"><span>Banyak kelas & mapel</span><span>Web & Android</span></div></div><small>Dirancang untuk keseharian guru Indonesia.</small></section><section className="login-card"><div className="eyebrow">SELAMAT DATANG</div><h2>Mulai hari mengajar Anda</h2><p>Masuk untuk mengakses data pribadi Anda.</p>{configured?<form onSubmit={async e=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{await signInWithEmailAndPassword(auth,f.get('email'),f.get('password'))}catch{setNotice('Login gagal. Periksa email, password, dan koneksi.')}finally{setBusy(false)}}}><Field label="Email" name="email" type="email" required autoComplete="username"/><Field label="Password" name="password" type="password" required autoComplete="current-password"/><button className="primary full" disabled={busy}>Masuk <ArrowRight size={18}/></button></form>:<div className="callout"><Cloud size={22}/><div><strong>Firebase belum dihubungkan</strong><p>Anda tetap bisa mencoba semua alur dengan data contoh di perangkat ini.</p></div></div>}<button className="secondary full" onClick={startDemo}><FlaskConical size={18}/>Coba versi demo</button><small>Mode demo tersimpan hanya di browser/perangkat ini dan tidak tersinkron.</small>{notice&&<p role="alert" className="error">{notice}</p>}</section></main>;
 return <div className="app"><aside className="sidebar"><div className="brand"><span><BookOpen/></span>Ruang Guru</div><div className="workspace-label">RUANG KERJA PRIBADI</div><nav>{menus.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setSearch('')}}><Icon size={20}/>{label}{page===id&&<ChevronRight size={16}/>}</button>)}</nav><div className="sidebar-note"><GraduationCap/><strong>Satu guru, banyak ruang belajar.</strong><p>Semua kelas dan mapel Anda tetap tertata.</p></div><button className="account" onClick={logout}><div className="avatar">{(data.profile.name||'G').slice(0,1)}</div><span><strong>{data.profile.name||'Guru'}</strong><small>Keluar dari akun</small></span><LogOut size={17}/></button></aside><div className="main"><header className="topbar"><span>{data.profile.school||'Ruang kerja guru'}</span><div><span className={'mode '+mode}>{mode==='demo'?<FlaskConical size={14}/>:<Cloud size={14}/>} {mode==='demo'?'Mode demo · lokal':'Firebase'}</span><span className="period">{data.profile.year} · {data.profile.semester}</span></div></header><main className="content"><div className="page-heading"><div><div className="eyebrow">{new Date().toLocaleDateString('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</div><h1>{menus.find(m=>m[0]===page)?.[1]}</h1><p>{page==='home'?'Selamat mengajar. Mulai dari pertemuan hari ini.':page==='classes'?'Kelola siswa sekali, gunakan di setiap mapel.':page==='settings'?'Identitas dan periode mengajar Anda.':'Catatan belajar untuk setiap kelas dan mata pelajaran.'}</p></div>{!['settings','classes','reports'].includes(page)&&<button className="primary" onClick={newMeeting}><Plus size={18}/>Pertemuan baru</button>}</div>
 {loading?<Empty title="Memuat data Anda…"/>:<>
 {page!=='settings'&&<div className="filters"><Field label="Kelas"><select aria-label="Pilih kelas" value={cid} onChange={e=>{setClassId(e.target.value);setSubjectId('');setSelected('')}}>{!data.classes.length&&<option value="">Belum ada kelas</option>}{data.classes.map(c=><option key={c.id} value={c.id}>{c.name} · {c.level}</option>)}</select></Field><Field label="Mata pelajaran"><select aria-label="Pilih mapel" value={sid} onChange={e=>{setSubjectId(e.target.value);setSelected('')}}>{!subjects.length&&<option value="">Belum ada mapel</option>}{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><span className="phase">{cls?'Fase '+cls.phase:'Atur kelas untuk mulai'}<small>{students.length} siswa terdaftar</small></span></div>}
 {page==='home'&&<><div className="stats">{[[data.classes.length,'Kelas dikelola',Users],[data.subjects.length,'Mata pelajaran',BookOpen],[allCurrent.length,'Pertemuan semester ini',CalendarDays],[allCurrent.filter(m=>m.journal?.tp).length,'Jurnal terisi',NotebookPen]].map(([n,label,Icon])=><div className="stat" key={label}><Icon/><strong>{n}</strong><span>{label}</span></div>)}</div><div className="dashboard-grid"><section className="panel"><div className="section-title"><div><h2>Pertemuan terbaru</h2><p>{subject?.name||'Mapel Anda'} · {cls?.name||'Kelas Anda'}</p></div><button className="text-button" onClick={()=>setPage('meetings')}>Lihat semua <ArrowRight size={16}/></button></div>{meetings.length?meetings.slice(0,4).map(m=><MeetingRow key={m.id} m={m} onClick={()=>openMeeting(m)}/>):<Empty title="Pertemuan pertama dimulai di sini" body="Buat pertemuan untuk mencatat absen, jurnal, dan asesmen." action={<button className="primary" onClick={newMeeting}><Plus size={17}/>Buat pertemuan</button>}/>}</section><section className="focus-card"><div className="eyebrow">PEMBELAJARAN MENDALAM</div><h2>Dari memahami,<br/>menjadi bermakna.</h2><p>Catat pengalaman belajar sesuai kebutuhan pertemuan Anda.</p>{['Memahami','Mengaplikasi','Merefleksi'].map((s,i)=><div className="step" key={s}><span>0{i+1}</span>{s}</div>)}<small>Tahap dapat dirancang dalam beberapa pertemuan.</small></section></div><div className="tip"><NotebookPen size={20}/><span><strong>Alur mengajar yang sederhana</strong> Pilih kelas & mapel, buat pertemuan, lalu lengkapi absen, jurnal, dan penilaian.</span></div></>}
 {['meetings','journal','grades'].includes(page)&&<><div className="meeting-select"><Field label="Pertemuan"><select value={current?.id||''} onChange={e=>setSelected(e.target.value)}><option value="">Pilih pertemuan…</option>{meetings.map(m=><option key={m.id} value={m.id}>{m.date} · {m.time} · {m.topic}</option>)}</select></Field>{current&&<span className="badge">{current.roster.length} siswa</span>}</div>{current?<section className="panel"><div className="section-title"><div><h2>{current.topic}</h2><p>{current.date} · {current.time} · {current.duration} JP</p></div><div className="tabs">{[['meetings','Absen'],['journal','Jurnal'],['grades','Penilaian']].map(([p,label])=><button key={p} className={page===p?'selected':''} onClick={()=>setPage(p)}>{label}</button>)}</div></div>{page==='meetings'?<Attendance key={current.id} meeting={current} busy={busy} onSave={m=>save('meetings',m)}/>:page==='journal'?<Journal key={current.id} meeting={current} busy={busy} onSave={m=>save('meetings',m)}/>:<Grades key={current.id} meeting={current} busy={busy} onSave={m=>save('meetings',m)}/>}</section>:<section className="panel">{meetings.length?meetings.map(m=><MeetingRow key={m.id} m={m} onClick={()=>openMeeting(m,page)}/>):<Empty title="Belum ada pertemuan" body="Setiap mapel memiliki absensi dan jurnalnya sendiri." action={<button className="primary" onClick={newMeeting}>Buat pertemuan pertama</button>}/>}</section>}</>}
 {page==='classes'&&<><div className="actions"><button className="primary" onClick={()=>setModal({type:'class'})}><Plus size={17}/>Tambah kelas</button><button className="secondary" onClick={()=>setModal({type:'subject'})}><Plus size={17}/>Tambah mapel</button><button className="secondary" disabled={!cls} onClick={()=>setModal({type:'student'})}><Plus size={17}/>Tambah siswa</button></div><section className="panel"><div className="section-title"><div><h2>Daftar siswa {cls?.name}</h2><p>{subjects.map(s=>s.name).join(' · ')||'Belum ada mapel untuk kelas ini'}</p></div><label className="search"><Search size={17}/><input placeholder="Cari nama atau NIS" aria-label="Cari siswa" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>{students.length?<div className="table-wrap"><table><thead><tr><th>No.</th><th>Nama siswa</th><th>NIS / nomor induk</th><th>Aksi</th></tr></thead><tbody>{students.filter(s=>(s.name+' '+s.nis).toLowerCase().includes(search.toLowerCase())).map((s,i)=><tr key={s.id}><td>{i+1}</td><td><strong>{s.name}</strong></td><td>{s.nis||'—'}</td><td><button className="text-button" onClick={()=>setModal({type:'student',value:s})}>Edit</button></td></tr>)}</tbody></table></div>:<Empty title="Siapkan daftar siswa" body="Tambahkan siswa ke kelas ini untuk mulai mencatat pertemuan."/>}</section><section className="panel space"><h2>Kelas & pengampu mapel</h2><div className="class-grid">{data.classes.map(c=><div key={c.id} className="class-card"><strong>{c.name} <span className="badge">{c.level} · Fase {c.phase}</span></strong><p>{data.subjects.filter(s=>s.classIds.includes(c.id)).map(s=>s.name).join(', ')||'Belum ada mapel'}</p><button className="text-button" onClick={()=>setModal({type:'class',value:c})}>Edit kelas</button></div>)}</div><div className="chips">{data.subjects.map(s=><button className="secondary" key={s.id} onClick={()=>setModal({type:'subject',value:s})}>Edit {s.name}</button>)}</div></section></>}
 {page==='reports'&&<Reports meetings={meetings} cls={cls} subject={subject} profile={data.profile} exportRows={exportRows}/>}
 {page==='settings'&&<section className="panel narrow"><SettingsForm profile={data.profile} save={v=>save('profile',v)} busy={busy}/><div className="callout"><Cloud size={22}/><div><strong>{mode==='demo'?'Anda sedang mencoba mode demo':'Data tersimpan di Firebase'}</strong><p>{mode==='demo'?'Data demo hanya berada di perangkat ini. Setelah Firebase dikonfigurasi, masuk dengan akun pribadi untuk mulai menyimpan data online.':'Gunakan akun yang sama pada web dan Android untuk mengakses data Anda.'}</p></div></div><button className="secondary" onClick={logout}><LogOut size={17}/>Keluar dari akun</button><h3 className="space">Acuan penyusunan jurnal</h3><p className="muted">CP, TP, kriteria, dan rubrik diisi guru sesuai mapel, fase, dan dokumen sekolah. Aplikasi tidak menghasilkan CP resmi atau nilai rapor otomatis.</p><a href="https://kurikulum.kemendikdasmen.go.id/pembelajaran-mendalam" target="_blank" rel="noreferrer">Panduan Pembelajaran Mendalam Kemendikdasmen ↗</a></section>}
 </>}
 </main><footer>Ruang Guru <span>Catatan kecil, pembelajaran bermakna.</span></footer></div>{notice&&<div className="toast" role="status"><Check size={18}/>{notice}<button onClick={()=>setNotice('')} aria-label="Tutup pesan"><X size={16}/></button></div>}{modal&&<Modal title={{class:'Kelola kelas',subject:'Kelola mata pelajaran',student:'Kelola siswa',meeting:'Pertemuan baru'}[modal.type]} onClose={()=>setModal(null)}><Editor key={modal.value?.id||modal.type} modal={modal} data={data} cls={cls} subject={subject} students={students} busy={busy} onSubmit={async(kind,v)=>{try{if(kind==='meetings'){validateMeeting(v);if(data.meetings.some(m=>m.classId===v.classId&&m.subjectId===v.subjectId&&m.date===v.date&&m.time===v.time&&m.year===v.year&&m.semester===v.semester))throw Error('Pertemuan dengan tanggal dan jam tersebut sudah ada.')}if(kind==='subjects'&&(!v.name||!v.classIds.length))throw Error('Isi nama dan pilih minimal satu kelas.');if(kind==='students'&&v.nis&&data.students.some(s=>s.id!==v.id&&s.classId===v.classId&&s.nis===v.nis))throw Error('NIS tersebut sudah digunakan di kelas ini.');if(await save(kind,v)){setModal(null);if(kind==='meetings')openMeeting(v);if(kind==='classes')setClassId(v.id)}}catch(e){setNotice(e.message)}}}/></Modal>}</div>
}



